import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/SessionProvider";
import ChatBot from "@/components/ChatBot";
import CustomCursor from "@/components/CustomCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          {children}
          <ChatBot apiKey="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" />
          <CustomCursor />
        </SessionProvider>
      </body>
    </html>
  );
}
